# Imports

In [68]:
import pandas as pd
import numpy as np

# Load Dataset

In [61]:
df = pd.read_csv('dataset/global_cattle_milk_yield_prediction_dataset.csv')

# Analisando os Dados

In [62]:
df1 = df.loc[(df['Country'] =='BR'), :]
df1 = df1.drop(['Region', 'HS_Vaccine',
       'BQ_Vaccine', 'Anthrax_Vaccine', 'IBR_Vaccine', 'BVD_Vaccine',
       'Rabies_Vaccine', 'Farm_ID'], axis=1).reset_index()
df1.shape

(16541, 30)

In [63]:
df1.head().T

,0,1,2,3,4
index,3,14,51,73,77
Cattle_ID,CATTLE_000004,CATTLE_000015,CATTLE_000052,CATTLE_000074,CATTLE_000078
Breed,Fleckvieh,Hariana,Jersey,Red_Poll_Africa,Girolando
Country,BR,BR,BR,BR,BR
Climate_Zone,Tropical,Continental,Subtropical,Subtropical,Tropical
Management_System,Semi_Intensive,Pastoral,Extensive,Intensive,Semi_Intensive
Age_Months,73,142,28,142,86
Weight_kg,260.5,532.3,401.0,332.6,620.6
Parity,5,2,5,6,1
Lactation_Stage,Late,Mid,Early,Mid,Early
Days_in_Milk,249,32,363,299,307
Feed_Type,Crop_Residues,Dry_Fodder,Silage,Concentrates,Concentrates
Feed_Quantity_kg,10.6,10.4,12.3,14.6,9.4
Feeding_Frequency,1,3,5,4,3
Water_Intake_L,90.3,51.5,44.8,81.3,62.5
Walking_Distance_km,3.6,3.57,0.5,1.23,3.52
Grazing_Duration_hrs,6.8,11.0,6.6,6.0,7.4
Rumination_Time_hrs,7.1,11.0,9.7,10.4,11.0
Resting_Hours,8.9,9.1,5.0,12.7,7.6
Ambient_Temperature_C,34.0,16.0,5.8,25.0,40.0
Humidity_percent,34.9,46.0,43.5,45.7,57.3
Season,Spring,Summer,Winter,Autumn,Summer
Housing_Score,0.69,0.82,0.93,0.62,0.69
FMD_Vaccine,0,0,1,1,1
Brucellosis_Vaccine,0,0,0,1,0
Previous_Week_Avg_Yield,10.63,0.25,11.5,3.21,6.33
Body_Condition_Score,4.0,2.5,4.0,3.5,4.5
Milking_Interval_hrs,8,24,8,12,8
Date,2023-07-07,2022-09-14,2022-01-25,2022-09-10,2023-08-29
Milk_Yield_L,12.74,2.24,11.09,2.68,5.28

In [64]:
df1['Date'] = pd.to_datetime(df1['Date'])

df1['FMD_Vaccine'] = df1['FMD_Vaccine'].apply(lambda x: 'no' if x == 0 else 'yes') 
df1['Brucellosis_Vaccine'] = df1['Brucellosis_Vaccine'].apply(lambda x: 'no' if x == 0 else 'yes') 

df1.dtypes

index                               int64
Cattle_ID                             str
Breed                                 str
Country                               str
Climate_Zone                          str
Management_System                     str
Age_Months                          int64
Weight_kg                         float64
Parity                              int64
Lactation_Stage                       str
Days_in_Milk                        int64
Feed_Type                             str
Feed_Quantity_kg                  float64
Feeding_Frequency                   int64
Water_Intake_L                    float64
Walking_Distance_km               float64
Grazing_Duration_hrs              float64
Rumination_Time_hrs               float64
Resting_Hours                     float64
Ambient_Temperature_C             float64
Humidity_percent                  float64
Season                                str
Housing_Score                     float64
FMD_Vaccine                           str
Brucellosis_Vaccine                   str
Previous_Week_Avg_Yield           float64
Body_Condition_Score              float64
Milking_Interval_hrs                int64
Date                       datetime64[us]
Milk_Yield_L                      float64
dtype: object

In [65]:
#conferindo valores NA e duplicados
df1.isna().sum()
df1.duplicated().sum()

np.int64(0)

# Análise Descritiva

### Variáveis Númericas

In [66]:
num_atributtes = df1.select_dtypes(include=['float64', 'int'])
num_atributtes.T

,0,1,2,3,4,5,6,7,8,9,...,16531,16532,16533,16534,16535,16536,16537,16538,16539,16540
index,3.00,14.00,51.00,73.00,77.00,84.00,121.00,135.00,144.00,146.00,...,249837.00,249857.00,249859.00,249890.00,249898.00,249930.00,249978.00,249984.00,249985.00,249988.00
Age_Months,73.00,142.00,28.00,142.00,86.00,99.00,104.00,110.00,78.00,101.00,...,101.00,105.00,64.00,29.00,115.00,57.00,85.00,137.00,122.00,93.00
Weight_kg,260.50,532.30,401.00,332.60,620.60,484.00,311.40,621.70,553.50,250.90,...,275.80,459.00,644.40,260.30,642.10,532.90,481.60,334.60,511.60,418.00
Parity,5.00,2.00,5.00,6.00,1.00,4.00,1.00,1.00,1.00,6.00,...,6.00,4.00,5.00,5.00,6.00,4.00,5.00,2.00,2.00,5.00
Days_in_Milk,249.00,32.00,363.00,299.00,307.00,201.00,260.00,42.00,364.00,242.00,...,239.00,146.00,182.00,69.00,157.00,1.00,92.00,245.00,70.00,51.00
Feed_Quantity_kg,10.60,10.40,12.30,14.60,9.40,17.20,11.00,12.60,12.90,7.60,...,6.20,15.00,10.70,12.80,14.80,12.60,17.30,17.50,12.00,5.00
Feeding_Frequency,1.00,3.00,5.00,4.00,3.00,1.00,3.00,2.00,3.00,3.00,...,4.00,1.00,2.00,5.00,2.00,3.00,3.00,1.00,5.00,2.00
Water_Intake_L,90.30,51.50,44.80,81.30,62.50,76.40,70.20,75.90,65.90,60.40,...,64.80,45.60,86.10,69.20,105.50,66.30,68.70,61.20,70.20,33.90
Walking_Distance_km,3.60,3.57,0.50,1.23,3.52,3.20,1.70,3.27,3.20,3.44,...,0.50,1.34,5.99,0.96,2.11,4.31,6.19,4.57,3.71,0.50
Grazing_Duration_hrs,6.80,11.00,6.60,6.00,7.40,7.60,3.00,7.30,4.20,1.40,...,12.90,7.50,7.90,4.80,6.80,1.40,4.10,8.70,1.00,5.50
Rumination_Time_hrs,7.10,11.00,9.70,10.40,11.00,5.90,5.70,6.30,8.60,8.70,...,11.40,10.60,9.00,6.10,7.30,6.30,7.90,7.30,7.80,4.00
Resting_Hours,8.90,9.10,5.00,12.70,7.60,7.50,12.40,14.50,12.70,9.40,...,7.50,10.50,8.40,15.10,12.70,11.30,13.50,12.10,10.70,15.50
Ambient_Temperature_C,34.00,16.00,5.80,25.00,40.00,43.30,7.90,17.20,2.90,26.00,...,13.00,6.60,22.10,25.20,17.30,15.30,34.40,16.10,8.50,26.30
Humidity_percent,34.90,46.00,43.50,45.70,57.30,55.30,72.50,35.60,67.00,80.30,...,63.40,55.40,70.90,69.50,100.00,93.00,71.20,78.10,43.30,100.00
Housing_Score,0.69,0.82,0.93,0.62,0.69,0.47,0.72,0.36,0.44,0.39,...,0.83,0.83,0.82,0.59,0.75,0.69,0.50,0.75,0.40,0.31
Previous_Week_Avg_Yield,10.63,0.25,11.50,3.21,6.33,14.31,0.16,10.93,1.36,2.31,...,14.00,15.48,9.55,3.00,12.64,5.20,0.00,3.50,17.07,9.45
Body_Condition_Score,4.00,2.50,4.00,3.50,4.50,4.50,2.50,2.50,3.00,3.50,...,3.50,2.50,4.50,2.50,3.50,3.50,4.00,2.50,3.00,3.50
Milking_Interval_hrs,8.00,24.00,8.00,12.00,8.00,24.00,12.00,12.00,24.00,12.00,...,24.00,12.00,12.00,24.00,12.00,12.00,12.00,12.00,12.00,24.00
Milk_Yield_L,12.74,2.24,11.09,2.68,5.28,11.15,1.93,11.19,2.78,4.65,...,14.67,16.23,10.24,4.49,12.87,5.37,0.00,4.06,17.82,8.83

### Variáveis Categóricas

In [67]:
cat_atributtes = df1.select_dtypes(exclude=['float64', 'int', 'datetime64'])
cat_atributtes.T

,0,1,2,3,4,5,6,7,8,9,...,16531,16532,16533,16534,16535,16536,16537,16538,16539,16540
Cattle_ID,CATTLE_000004,CATTLE_000015,CATTLE_000052,CATTLE_000074,CATTLE_000078,CATTLE_000085,CATTLE_000122,CATTLE_000136,CATTLE_000145,CATTLE_000147,...,CATTLE_249838,CATTLE_249858,CATTLE_249860,CATTLE_249891,CATTLE_249899,CATTLE_249931,CATTLE_249979,CATTLE_249985,CATTLE_249986,CATTLE_249989
Breed,Fleckvieh,Hariana,Jersey,Red_Poll_Africa,Girolando,Sahiwal,Gir,Brown_Swiss,Africander,Ankole,...,Milking_Shorthorn,Jersey_Zebu_Cross,Kenana,Hariana,Zebu_Cross_Brazil,Boran,Ankole,Australian_Milking_Zebu,Fleckvieh,Red_Sindhi
Country,BR,BR,BR,BR,BR,BR,BR,BR,BR,BR,...,BR,BR,BR,BR,BR,BR,BR,BR,BR,BR
Climate_Zone,Tropical,Continental,Subtropical,Subtropical,Tropical,Subtropical,Continental,Temperate,Temperate,Arid,...,Temperate,Tropical,Mediterranean,Temperate,Mediterranean,Subtropical,Subtropical,Mediterranean,Tropical,Subtropical
Management_System,Semi_Intensive,Pastoral,Extensive,Intensive,Semi_Intensive,Extensive,Intensive,Pastoral,Pastoral,Semi_Intensive,...,Pastoral,Intensive,Intensive,Extensive,Intensive,Semi_Intensive,Extensive,Mixed,Mixed,Pastoral
Lactation_Stage,Late,Mid,Early,Mid,Early,Early,Early,Late,Mid,Early,...,Mid,Early,Early,Early,Early,Early,Late,Late,Mid,Mid
Feed_Type,Crop_Residues,Dry_Fodder,Silage,Concentrates,Concentrates,Crop_Residues,Silage,Mixed_Feed,Green_Fodder,Dry_Fodder,...,Dry_Fodder,Hay,Green_Fodder,Silage,Crop_Residues,Dry_Fodder,Mixed_Feed,Green_Fodder,Pasture_Grass,Green_Fodder
Season,Spring,Summer,Winter,Autumn,Summer,Monsoon,Winter,Monsoon,Autumn,Spring,...,Autumn,Winter,Spring,Spring,Autumn,Summer,Spring,Autumn,Summer,Summer
FMD_Vaccine,no,no,yes,yes,yes,yes,no,no,no,no,...,no,yes,yes,yes,yes,yes,yes,no,yes,no
Brucellosis_Vaccine,no,no,no,yes,no,yes,yes,yes,yes,yes,...,yes,yes,no,yes,no,yes,yes,yes,yes,no